** Attention ** : le cours est à lire dans son intégralité pour le prochain TD. Si vous avez des questions, n'hésitez pas à les poser au prochain TD... car au TD suivant, vous aurez une interrogation !

**Les tableaux**

In [9]:
#Initialisation pour utiliser des "vrais" tableaux
import numpy as np
tableau = np.empty(10)
print(tableau)
print(len(tableau))
print(tableau[4])
autretableau = np.array([1,2,4,6,7])
print(autretableau)
print(autretableau[4])

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
10
0.0
[1 2 4 6 7]
7


In [4]:
tableau0 = np.zeros(10)
print(tableau0)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


**Exercices ** 
1. Rechercher si un élément est présent dans un tableau. 
2. Vérifier que deux tableaux sont égaux. 
3. Vérifier qu'un tableau est le préfixe d'un autre. 
4. Rechercher le minimum d'un tableau.
5. Faire la somme des éléments d'un tableau.
6. Calculer la moyenne des éléments d'un tableau.
7. Multiplier tous les éléments d'un tableau par un facteur donné.
8. Décaler tous les éléments d'un tableau à droite.
9. Retourner un tableau contentant, case par case, le minimum de deux autres tableaux. 
10. Faire la somme des éléments dans les cases impaires d'un tableau. 