** Attention ** : le cours est à lire dans son intégralité pour le prochain TD. Si vous avez des questions, n'hésitez pas à les poser au prochain TD... car au TD suivant, vous aurez une interrogation !

**Les tableaux**

In [1]:
#Initialisation pour utiliser des "vrais" tableaux
import numpy as np
tableau = np.empty(10)
print(tableau)
print(len(tableau))
print(tableau[4])
autretableau = np.array([1,2,4,6,7])
print(autretableau)
print(autretableau[4])

[  1.08835389e-316   0.00000000e+000   6.90066334e-310   6.90069405e-310
   6.90068060e-310   6.90069405e-310   1.12638588e-316   0.00000000e+000
   6.90070023e-310   6.36598737e-311]
10
6.90068060163e-310
[1 2 4 6 7]
7


In [2]:
tableau0 = np.zeros(10)
print(tableau0)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


**Exercices ** 
1. Rechercher si un élément est présent dans un tableau. 
2. Vérifier que deux tableaux sont égaux. 
3. Vérifier qu'un tableau est le préfixe d'un autre. 
4. Rechercher le minimum d'un tableau.
5. Faire la somme des éléments d'un tableau.
6. Calculer la moyenne des éléments d'un tableau.
7. Multiplier tous les éléments d'un tableau par un facteur donné.
8. Décaler tous les éléments d'un tableau à droite.
9. Retourner un tableau contentant, case par case, le minimum de deux autres tableaux. 
10. Faire la somme des éléments dans les cases impaires d'un tableau. 

In [3]:
# Initialisation du tableau test 
tableautest = np.array([1,2,3,5,6,7,9])
print(tableautest)

[1 2 3 5 6 7 9]


In [4]:
# Correction exercice 1 
def rechercherElt(elt, tab):
    present = False
    for i in tab :
        if i == elt:
            present= True
    return present
        
print(rechercherElt(15, tableautest))
print(rechercherElt(3, tableautest))

False
True


In [5]:
#Correction exercice 1 (un peu compliquée, et ne fonctionne pas 
# si l'élément est dans la dernière case du tableau !)

def rechercherElement(element, tableau):
    finBoucle = False
    compteur = 0
    while finBoucle == False:
        if tableau[compteur] == element:
            finBoucle = True
        if compteur == len(tableau) - 1:
            finBoucle = True
        compteur+=1
    
    if compteur < len(tableau):
        return True
    else:
        return False
    
rechercherElement(3, tableautest)


True

In [6]:
#Correction exercice 1 avec un while

def rechercherElementPropre(elt, tab):
    i = 0
    b = False
    while i < len(tab) and not b:
        if tab[i] == elt:
            b = True
        i+=1
    return b

print(rechercherElementPropre(3, tableautest))
print(rechercherElementPropre(15, tableautest))

            
        
    

True
False


In [7]:
# Autre série de tableaux pour les tests
test1 = np.array([1, 2, 3, 4, 5, 7, 9])
test2 = np.array([1, 3])
test3 = np.array([1, 2])

In [8]:
# Correction exercice 2 
def comparaison(tab1, tab2):
    pareil = True
    if len(tab1) == len(tab2):
        i=0
        while i < len(tab1) and pareil == True:
            if tab1[i] != tab2[i]:
                pareil = False
            i+=1
    else:
        pareil = False
    return(pareil)

print(comparaison(test1, test2))
print(comparaison(test1, test1))

False
True


In [9]:
# Correction exercice 3 
def estPrefixe(t1, t2):
    result = True
    if len(t1) > len(t2):
        result = False
    else:
        i = 0
        while i < len(t1) and result:
            if t1[i] != t2[i]:
                result = False
            i += 1
    return result
    
print(estPrefixe(test2, test1) == False)
print(estPrefixe(test3, test1) == True)


# estPrefixeGenerique rend obsolète le premier test de 
# estPrefixe qui pourrait donc être amélioré. 

def estPrefixeGenerique(t1,t2):
    if len(t1)<len(t2):
        result = estPrefixe(t1,t2)
    else:
        result = estPrefixe(t2,t1)
    return(result)
print(estPrefixeGenerique(test2, test1) == False)
print(estPrefixeGenerique(test3, test1) == True)
print(estPrefixeGenerique(test1, test2) == False)
print(estPrefixeGenerique(test1, test3) == True)

True
True
True
True
True
True


In [10]:
# Exercice 4 
def minimun (tab):
    minimun = tab[0]
    for i in range (len(tab)):
        if minimun > tab[i]:
            minimun = tab [i]
            
    return minimun
print (minimun (test1))

1


In [11]:
# Exercice 5
def somme(tab):
    somme = 0
    for i in range(len(tab)):
        somme = somme + tab[i]
    return(somme)

print(somme(test1))

31


In [12]:
# Exercice 6 
def moyenne(tab):
    if len(tab) != 0:
        moy = somme(tab)/len(tab)
    else:
        return 0
    return(moy)

print(moyenne(test2))

2.0


La suite des exercices est corrigée dans le TD13. 