**Suite des exercices du TD12** 

Ex 7. Multiplier tous les éléments d'un tableau par un facteur donné.

EX 8. Décaler tous les éléments d'un tableau à droite.

Ex 9. Retourner un tableau contentant, case par case, le minimum de deux autres tableaux. 

Ex 10. Faire la somme des éléments dans les cases impaires d'un tableau. 

In [2]:
#Exercice 7 
import numpy as np

def multtab(tab, m):
    for i in range(len(tab)):
        tab[i] *= m
        
    return tab
t1 = np.array([2,6,34,42])

print(multtab(t1, 2))

[ 4 12 68 84]


In [3]:
#Exercice 8 
def decaleTab(tab):
    i = len(tab) - 1
    premElem = tab[i]
    while i > 0:
        tab[i] = tab[i - 1]
        i -= 1
    tab[0] = premElem
    return(tab)

t1 = np.array([2, 4, 42, 76, 89, 69])
print(decaleTab(t1))

[69  2  4 42 76 89]


In [4]:
#Exercice 9 
def minimundetable(t1,t2):
    t3=np.empty(len(t1))
    for i in range(len(t1)):
        if t1[i]<t2[i]:
            t3[i]=t1[i]
        else:
            t3[i]=t2[i]
    return t3
t1 = np.array([2,6,34,42])
t2 = np.array([2,7,0,18])
print (minimundetable(t1,t2))

[  2.   6.   0.  18.]


In [7]:
# Exercice 10 
def sommeimp(tab):
    r = 0
    for i in range(1, len(tab), 2):
        r += tab[i]
    return r

t1 = np.array([2, 4, 42, 76, 89, 69,123])
print(sommeimp(t1))



149


**Exercices - série 2**

2.1. Retourner l'indice de la dernière occurrence du minimum d'un tableau.

2.2. Remplacer tous les éléments aux indices premiers par un 0.

2.3. Soit un tableau de notes (floats entre 0.0 et 20.0) de taille N, et un tableau d'entiers de taille M. Faire la moyenne des notes du premier tableaux en ne considérant que celles aux indices présents dans le second tableau. Pour cet exercice, vous écrirez les pré- et post-conditions. 

2.4. Inverser un tableau.

2.5. Rechercher l'indice de la nième occurrence d'une valeur dans un tableau. 



In [9]:
#Exercice 2.1 
def lastIndexOfMin(tab):
    min = tab[0]
    indiceMin = 0
    i = 0
    while i < len(tab):
        if tab[i] <= min:
            min = tab[i]
            indiceMin = i
        i += 1
    return indiceMin
test = np.array([1,56,-4,42,64,54,56,69,13,-4,17])

lastIndexOfMin(test)

9

In [10]:
#Exercice 2.3 
def moyenneTableau(t1, t2):
    somme = 0
    for i in range(len(t2)):
        somme += t1[t2[i]]
        
    return somme/len(t2)

t1 = np.array([10,12,14,16])
t2 = np.array([2,1])

print(moyenneTableau(t1, t2))


13.0


In [13]:
#Exercice 2.4
def inverser_tableau(tab):
    i = 0
    while i < len(tab) - 1 - i:
        #temp = tab[i]
        #tab[i] = tab[len(tab) - 1 - i]
        #tab[len(tab) - 1 - i] = temp
        #Synthèse en une ligne :
        tab[i], tab[len(tab) - 1 - i] = tab[len(tab) - 1 - i], tab[i]
        i = i+1
        
    return tab

t1 = np.array([1, 2, 3, 4])
print(inverser_tableau(t1))

[4 3 2 1]


In [1]:
#Problème

def moyennes_par_groupe(notes, nbEtu):
    """
    :entrée notes: tableau de float
    :entrée nbEtu: tableau d'int
    :sortie moy: tableau de float
    :pré-cond:
       - la somme des éléments de nbEtu est égale à len(notes)
       - notes[0 : nbEtu[0]] contient les notes du premier groupe ;
         notes[nbEtu[0] : nbEtu[0] + nbEtu[1]] contient les notes du
         deuxième groupe, et ainsi de suite...
    :post-cond:
       - len(moy) = len(nbEtu)
       - ∀ i ∈ [0;len(moy)[,  moy[i] contient la moyenne des étudiants
         du (i+1)ème groupe

    >>> moyennes_par_groupes([11.0, 9.0, 10.0, 15.0, 16.0, 2.0, 3.0, 4.0],
                             [3, 2, 3])
    array([10.0, 15.5, 3.0])
    """
