In [23]:
import numpy as np

In [34]:
tvide = np.array([])
trand = np.array([9, 3, 1, 8, 4, 2, 5, 7, 6, 0])
tinv = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [25]:
# Algorithmes utilitaires
def rechercheMin(tab, i, j):
    """
    :entree-sortie tab: un tableau d'entiers
    :entrees i, j: indices bornant la recherche (i inclus, j exclus)
    :pre-cond: i < j
    :post-cond: retourne l'indice du minimum d'une section de tableau
                comprise entre i inclus et j exclus
    """
    mini = tab[i]
    indmini = i
    for indice in range (i,j):
        if tab[indice]<mini:
            mini = tab[indice]
            indmini = indice
    return indmini

def decalageAdroite(tab, i, j):
    
    for k in range (j,i,-1):
        tab [k]=tab[k-1]
    
# Tri par insertion avec recherche du minimum et décalage à droite    
def triinsertion(tab):
    
    for i in range (len(tab)):
        indmini=rechercheMin(tab, i, len(tab))
        valmini= tab[indmini]
        decalageAdroite(tab, i, indmini)
        tab[i]=valmini

print(trand)
triinsertion (trand)
print (trand)
print(tvide)
triinsertion (tvide)
print (tvide)
print(tinv)
triinsertion (tinv)
print (trand)
    

[9 3 1 8 4 2 5 7 6 0]
[0 1 2 3 4 5 6 7 8 9]
[]
[]
[9 8 7 6 5 4 3 2 1 0]
[0 1 2 3 4 5 6 7 8 9]


In [33]:
%%tutor --lang python3 
def rechercheMin(tab, i, j):
    mini = tab[i]
    indmini = i
    for indice in range (i,j):
        if tab[indice]<mini:
            mini = tab[indice]
            indmini = indice
    return indmini

def decalageAdroite(tab, i, j):
    for k in range (j,i,-1):
        tab [k]=tab[k-1]
    
def triinsertion(tab):    
    for i in range (len(tab)):
        indmini=rechercheMin(tab, i, len(tab))
        valmini= tab[indmini]
        decalageAdroite(tab, i, indmini)
        tab[i]=valmini

t = [1, 2, 6, 2, 0, 3, 7, 9, 4]
triinsertion(t)

In [38]:
tvide = np.array([])
trand = np.array([9, 3, 1, 8, 4, 2, 5, 7, 6, 0])
tinv = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

def triInserBis(tab):
    for i in range (1,len(tab)):
        for j in range(i):
            if tab[i] < tab[j]:
                temp = tab[i]
                decalageAdroite(tab,j,i)
                tab[j] = temp
                
print(tvide)
print(trand)
print(tinv)
triInserBis(tvide)
triInserBis(trand)
triInserBis(tinv)
print(tvide)
print(trand)
print(tinv)

[]
[9 3 1 8 4 2 5 7 6 0]
[9 8 7 6 5 4 3 2 1 0]
[]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [41]:
def estPresentDansTab(tab, val):
    '''
    :entree-sortie tab: un tableau d'entiers
    :entree val: int
    :sortie present: booléen
    :sortie nbOcc: int
    :post-cond: retourne present = False si la valeur n'est pas présente 
                dans le tableau et True si elle l'est.
                retourne également le nombre d'occurrences de la valeur
                dans le tableau 
    '''
    present=False
    compteur=0
    for i in range(len(tab)):
        if(tab[i]==val):
            compteur=compteur+1
            present=True
            
    return compteur,present

tabtest=np.array([1,2,7,3,1])
estPresentDansTab(tabtest,8)

(0, False)