In [3]:
import numpy as np

tableau = np.random.randint(10, size=(10))
print(tableau)


[5 2 9 6 2 6 1 6 5 6]


In [6]:
#Implémentation de l'algo de tri bulle avec un tableau ou une liste
liste = [5, 2, 9, 6, 2, 6, 1, 6, 5, 6]

def triBulle(tab):
    
    j = 0
    i = 0
    while i < len(tab):
        modif = 0
        while j < len(tab)-i-1:
            if tab[j] > tab[j+1]:
                tab[j],tab[j+1] = tab[j+1],tab[j]
                modif = 1
            j+=1
        if modif == 0:
            i = len(tab)
        i+=1
        j = 0
    
    
triBulle(tableau)
triBulle(liste)
print(tableau)
print(liste)

[1 2 2 5 5 6 6 6 6 9]
[1, 2, 2, 5, 5, 6, 6, 6, 6, 9]


In [18]:
tableau2D = np.zeros([10, 3], dtype='int')
print(len(tableau2D))
print(len(tableau2D[0]))

tableau2Drand = np.random.randint(10, size=(5,7))
print(tableau2D)
print(tableau2Drand)

10
3
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[3 6 0 3 2 6 7]
 [4 4 7 7 7 3 7]
 [4 8 9 8 7 8 8]
 [9 4 4 4 3 1 1]
 [9 9 0 5 6 1 1]]


In [15]:
def mult_tab(n, tab):
    for i in range(10):
        tab[i][0] = i
        tab[i][1] = n
        tab[i][2] = i*n
        
mult_tab(8, tableau2D)
print(tableau2D)

[[ 0  8  0]
 [ 1  8  8]
 [ 2  8 16]
 [ 3  8 24]
 [ 4  8 32]
 [ 5  8 40]
 [ 6  8 48]
 [ 7  8 56]
 [ 8  8 64]
 [ 9  8 72]]


In [19]:
def triligne(tab):
    for i in range (len(tab)):
        triBulle(tab[i])
print(tableau2Drand)    
triligne(tableau2Drand)
print(tableau2Drand)

[[3 6 0 3 2 6 7]
 [4 4 7 7 7 3 7]
 [4 8 9 8 7 8 8]
 [9 4 4 4 3 1 1]
 [9 9 0 5 6 1 1]]
[[0 2 3 3 6 6 7]
 [3 4 4 7 7 7 7]
 [4 7 8 8 8 8 9]
 [1 1 3 4 4 4 9]
 [0 1 1 5 6 9 9]]
